name: Unit test on Linux

permissions:
  contents: read

on: [workflow_call, workflow_dispatch]

jobs:
  unittest:
    runs-on: ["self-hosted", "linux", "no-gpu"]
    strategy:
      fail-fast: false
      matrix:
        version: ["reference_implementation", "optimized_implementation/kem", "optimized_implementation/kem-90s", "additional_implementation/TiMER_reference_implementation"]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Build
      working-directory: ${{ matrix.version }}
      run: cmake -B build -S . && cmake --build build -- -j4

    - name: Unit test
      working-directory: ${{ matrix.version }}
      run: cd build && ctest
